CREATE SCHEMA IF NOT EXISTS GWBACKEND;
CREATE TABLE IF NOT EXISTS GWBACKEND.USERS
(
    ID              BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_USER PRIMARY KEY (ID)
);